name: CI

on:
  push:
    branches:
      - main # Set your main branch name here

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can change the Node.js version if needed

    - name: Install Dependencies
      run: npm install

    - name: TypeScript Type Checking
      run: npm run type-check # Adjust your npm script name for type checking

    - name: Linting
      run: npm run lint # Adjust your npm script name for linting